name: Create Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    if: contains(github.event.head_commit.message, 'release')
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Initiating Release!

      - name: Create Tag
        run: git tag 3.1.5

      - name: Push Tag
        env:
          GITHUB_TOKEN: ${{ secrets.goldrate_release_token }}
        run: git push origin --tags

      - name: Fetch Latest Tag
        env:
          GITHUB_TOKEN: ${{ secrets.goldrate_release_token }}
        id: get_latest_tag
        run: |
          git fetch --tags
          LATEST_TAG=$(git describe --tags --abbrev=0)
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.goldrate_release_token }}
        with:
          tag_name: ${{ env.LATEST_TAG }}
          release_name: Release v${{ env.LATEST_TAG }}
          body: |
            Changes in this release:
              - First Change
          draft: false
          prerelease: false

      - name: Upload Android Release to Play Store
        uses: r0adkll/upload-google-play@v1.1.3
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.techrush_app.goldrate
          releaseFiles: app/release/app-release.aab
          track: production
          status: inProgress
